[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Chris Sims <chris@jcsi.ms>"]
edition = "2018"

[dependencies]
itertools = "0.8"
log = "0.4.8"
env_logger = "0.7.1"
regex = "1"
primes = "0.2.4"
